---

- hosts: all
  become: yes
  tasks:
  - name: Check ubuntu verison
    shell: |
      cat: /etc/system-release
    register: os_name
    ignore_errors: yes
  - debug:
      msg: "{{os_name.stdout}}"
